# Generated by Django 6.0 on 2026-01-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fist',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
